---
name: Deploy documentation 📖

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 18.x

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Use Node.js $NODE_VERSION
        uses: actions/setup-node@v3
        with:
          node-version: $NODE_VERSION
          cache: 'npm'

      - name: Install and Build 🔧
        run: |
          yarn install --frozen-lockfile
          mkdir html
          node src/cli.js -i schemata -o html/index.html
          ls -ltur html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: html
          branch: gh-pages
